travis:
  secure:
    BINSTAR_TOKEN: GsBTWxV3S2gzjDV26M5gro+0r4pNsaF/Vbt5+64DdEeADN/+g+gJwGXQfUCEQ65ZY/4i/aG2c7IOl5dT6MRB96caN/yyat/u3FFfovTbxebaN+5UOWZrraRTyk7e/f7OxCeM/M4rrLHcJLlUAA2bY/kC5vEdURvdJJ5glngcZxRuQMjuoe31oflPVKzDATgx25UodHecXOGKAj/4W+Hk/ENqCLdNy6kfI257rHTSy1CZ4Led/fK+7por4iWMgvySKISFZqWiS1wl1rw1QlJDVPimXjXXtWxDf+0Spel19ZJcGXkfrhzHPoaE0vQfpjX+YhZ5YrdPD7QOLv9FaU/G59Kctwvk2PlxsdAy5PCdsNj3cLXUCEH7O8FsdtBtmAGgaNSQHPmzIUQw4UpdMpWqOkdg9USERXdDfRQ7PE9NIjOMibI5ercxGwDc78E7+3pCvbPhWh/yvg6289wOU7k9MgVTM85ojiRcr20pT8am9OwBatdiJMaRNANEmubTB6Td1C9Svk+uoJ+eBoMWiZpEquW8AGow9eVWrgndEJzhESVJ9sFeJocMI59+e9MZ8zPh08mJMzdCmcBooRPAz+fCQIA0IyPBzgF/z86nQXPK7yD31XdlsteiZiG/QzW31Nlyl1Qd8NoMbH84bfSYCJze1jCRrQUh9dygMgvEEcSRtXk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
