travis:
  secure:
    BINSTAR_TOKEN: VUi66jo4nOi6NsuUn1JFGBaycNkCsWTvjjiBzEAJ8tlb2XonmuTaSD8yVnW8flKbHRjRzYx9nGoTiKZZyhiunD1tL5Jfec7Qtw2jjlw3Xk2FKdWOmgI0GHOohYNoHbSL6yozVAPWV+b7LKzjqYMvtUXaXlemiWEaJmAflb/H1n0Ck9mv3iVXp6eT8H2FY1K7pURSXBnb+dLjdVgBS1LvnAdcBDT9fLMQJXukePVFRq/2I1a7yRwzFwpLGL6AYAB1czuDjMLoQ5v4y3r+zKM+rIq5a3Y9cTsYEiW5aLheMS+apWjXIjPlmjMiqigrApZ7rQAM0OT4i6rOI0J2wmzSWREIYmpwLgK+ZuR5zvBwGl3nowOOSUHHGbCnSj34fVaCrbnMiJh+aJLuX+tn/wpeWFf/5a17P2yIeeAPD7NDdLs2pwYOPc88fe7TpkwVuFkBCQmiEPJuW/KghSL4j3Gc9i2QAVE/hBqocWuEShMevKFciF6ukXnYWtJ0hqpbKQ/BmeMvsK+mbPYxAomZcijWxfvhHeD0SaG39iXDKXhLryl9lS+ywqxCDZoXrBK2AH8nFaCJ67E2oISfzYwBb9/TciCHjs75tOhKdFGAsl8XqHjCgc7o9n5Zi8xRgvJzh8UgUQb9i5BY00H4SXIgSDDNrPGD5kKu8Z4icACG2clbb+M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
